language: cpp
compiler:
- gcc
- clang
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
install:
- sudo apt-get install -qq  qt5-qmake qtbase5-dev qttools5-dev qttools5-dev-tools qt5-default libqt5script5 libqt5scripttools5 qtdeclarative5-dev
- sudo apt-get install -qq libssl-dev
- qmake ChecksumJack.pro
- make
- make check
- sudo make install
